Repository gatsbyjs/gatsby-es, pull requests merged in 2019-11, with the labels that each got.

#123 Translate using-fragments.md documentation file
  docs/docs/using-fragments.md
Labels: in review

#128 Translated addign-markdown-pages.md with an exception in 'frontmatter' word
  docs/docs/adding-markdown-pages.md
Labels: in review

#135 Translation of adding-search-with-algolia completed
  docs/docs/adding-search-with-algolia.md
Labels: in review

#138 Fix some typos in blog-and-website-contributions.md
  docs/contributing/blog-and-website-contributions.md
Labels: Ready for review

#121 Translated to spanish "docs/docs/adding-forms.md"
  docs/docs/adding-forms.md
Labels: in review

#127 Docs/adding page transitions with plugin transition link
  docs/docs/adding-page-transitions-with-plugin-transition-link.md
Labels: in review

#134 [Add] Translation of `docs/docs/headless-cms.md`
  docs/docs/headless-cms.md
Labels: Ready for review

#137 Translate best-practices-for-orgs
  docs/docs/best-practices-for-orgs.md
Labels: Ready for review

#141 Translate building-with-components.md file
  docs/docs/building-with-components.md
Labels: in review

#146 Translated to Spanish the creating-plugins.md page
  docs/docs/creating-plugins.md
Labels: Ready for review

#140 Translates gatsby-on-linux.md documentation file
  docs/docs/gatsby-on-linux.md
Labels: Ready for review

#139 Translate quick-start.md documentation file
  docs/docs/quick-start.md
Labels: Ready for review

#136 Translation "api-proxy.md" ready for review
  docs/docs/api-proxy.md
Labels: Ready for review

#154 Update translation.md
  TRANSLATION.md
Labels: Ready for review

#147 Translated to Spanish the creating-global-styles.md page
  docs/docs/creating-global-styles.md
Labels: in review

#152 translate adding-website-functionality - es
  docs/docs/adding-website-functionality.md
Labels: Ready for review

#155 Translate deploying-and-hosting.md
  docs/docs/deploying-and-hosting.md
Labels: Ready for review

#144 Translated to Spanish the browser-support.md page
  docs/docs/browser-support.md
Labels: in review

#156 Translate gatsby-for-agencies.md
  docs/docs/gatsby-for-agencies.md
Labels: in review

#162 Docs/create prefixed 404s
  docs/docs/creating-prefixed-404-pages-for-different-languages.md
Labels: in review

#164 Translate `Building a Site with Authentication` to Spanish
  docs/docs/building-a-site-with-authentication.md
Labels: in review

#145 Translation of docs/docs/audit-with-lighthouse.md completed
  docs/docs/audit-with-lighthouse.md
Labels: in review

#159 Translate conceptual-guide.md to Spanish.
  docs/docs/conceptual-guide.md
Labels: Ready for review

#170 Translate caching.md doc file to Spanish #116
  docs/docs/caching.md
Labels: in review

#160 styling.md translation completed
  docs/docs/styling.md
Labels: in review

#161 Translate building a portfolio
  docs/docs/building-a-portfolio.md
Labels: Work in progress

#149 Translate building-apps-with-gatsby.md file
  docs/docs/building-apps-with-gatsby.md
Labels: in review

#51 Translate docs/docs/emotion.md
  docs/docs/emotion.md
Labels: in review

#148 Translated to Spanish the creating-a-local-plugin.md page
  docs/docs/creating-a-local-plugin.md
Labels: in review

#151 Translation completed cheat-sheet.md
  docs/docs/cheat-sheet.md
Labels: Ready for review

#157 translation complete.
  docs/docs/testing.md
Labels: in review

#158 translation complete testing-react-components.md
  docs/docs/testing-react-components.md
Labels: in review

#163 Translation completed client-data-fetching.md
  docs/docs/client-data-fetching.md
Labels: in review

#166 Spanish doc write pages.md without merges
  docs/docs/write-pages.md
Labels: in review

#184 Add translations for v1-release-notes and v2-release-notes.
  docs/docs/v1-release-notes.md
  docs/docs/v2-release-notes.md
Labels: Ready for review

#153 Trasnlate Docs/api specification
  docs/docs/api-specification.md
Labels: Ready for review

#168 Translate creating-a-starter.md file
  docs/docs/creating-a-starter.md
Labels: in review

#182 update what-you-dont-need-plugins-for.md
  docs/docs/what-you-dont-need-plugins-for.md
Labels: in review

#165 Translation of sass.md
  docs/docs/sass.md
Labels: in review

#150 Translate css-modules.md
  docs/docs/css-modules.md
Labels: in review

#180 Translated post-css.md
  docs/docs/post-css.md
Labels: in review

#186 translating content-and-data.md file
  docs/docs/content-and-data.md
Labels: in review

#187 Translating guides.md
  docs/docs/guides.md
Labels: Ready for review

#177 Translate winning-over-client.md
  docs/docs/winning-over-clients.md
Labels: in review

#176 Translate what-is-a-plugin.md
  docs/docs/what-is-a-plugin.md
Labels: in review

#181 Working with images translation into spanish
  docs/docs/working-with-images.md
Labels: in review
