Repository gatsbyjs/gatsby-es, pull requests merged in 2019-10, with the labels that each got.

#9 [WIP] Translating tutorial page one ⚠️
  docs/tutorial/part-one/index.md
Labels: documentation

#3 Translation of 'how-to-contribute' and 'css libraries...'
  docs/contributing/community-contributions.md
  docs/contributing/how-to-contribute.md
  docs/docs/css-libraries-and-frameworks.md
Labels: documentation

#13 Translation to Spanish 'how-to-pitch-gatsby.md'
  docs/contributing/how-to-pitch-gatsby.md
Labels: documentation

#10 chore(docs): Translation of how-to-file-an-issue - es
  docs/contributing/how-to-file-an-issue.md
Labels: Work in progress

#32 Adding how to contribute to translations, readme and glossary enhancements 💅
  CONTRIBUTING.MD
  MAINTAINERS.MD
  README.md
  TRANSLATION.md
Labels: Ready for review, documentation, enhancement

#46 Fixing links on navigation ⚙️
  CONTRIBUTING.MD
  README.md
  TRANSLATION.md
Labels: Ready for review, documentation, enhancement

#14 Update how-to-open-a-pull-request.md
  docs/contributing/how-to-open-a-pull-request.md
  docs/contributing/where-to-participate.md
Labels: Ready for review

#21 chore(docs): fixed broken link to blog
  docs/blog/2018-01-22-getting-started-gatsby-and-wordpress/index.md
Labels: Ready for review

#20 Update organize-a-gatsby-event.md
  docs/contributing/organize-a-gatsby-event.md
Labels: Ready for review, documentation

#36 [Translation] Blog with Netlify CMS tutorial
  docs/tutorial/blog-netlify-cms-tutorial/index.md
Labels: Ready for review

#27 Translate docs/css-in-js.md
  docs/docs/css-in-js.md
Labels: Work in progress, in review

#43 Translate community.md
  docs/contributing/community.md
Labels: in review

#86 Fix typos in CONTRIBUTING.MD
  CONTRIBUTING.MD
Labels: Ready for review

#77 add translate to seo.md
  docs/docs/seo.md
Labels: Ready for review, documentation

#98 update current translation progress issue
  CONTRIBUTING.MD
  README.md
Labels: Ready for review, documentation

#33 Translate docs/docs/mdx/getting-started.md
  docs/docs/mdx/getting-started.md
Labels: Work in progress

#37 Translate docs/docs/add-a-service-worker.md
  docs/docs/add-a-service-worker.md
Labels: Work in progress

#84 [Translation] contribution guidelines (docs/contributing/code-contribution)
  docs/contributing/code-contributions.md
Labels: Ready for review

#81 Translated docs/tutorials/theme-tutorials.md
  docs/tutorial/theme-tutorials.md
Labels: Ready for review

#102 Translation of docs/tutorial/wordpress-image-tutorial.md completed
  docs/tutorial/wordpress-image-tutorial.md
Labels: Ready for review

#100 add more words to the glossary
  TRANSLATION.md
Labels: Ready for review, documentation

#71 Translate tutorial/part-six
  docs/tutorial/part-six/index.md
Labels: Ready for review

#104 add @gusma, @xmartinezpujol and @anblave as code owner
  CODEOWNERS
Labels: Ready for review

#89 Added .gitignore
  .gitignore
Labels: in review

#79 Translated docs/tutorials/using-a-theme.md
  docs/tutorial/using-a-theme.md
Labels: in review

#48 Tutorial/part three
  docs/tutorial/part-three/index.md
Labels: in review

#57 chore(docs):Translation of setting-up-your-local-dev-environment - es
  docs/contributing/setting-up-your-local-dev-environment.md
Labels: in review

#94 Translation of creating-a-sitemap.md completed
  docs/docs/creating-a-sitemap.md
Labels: in review

#61 Adding translation to faster-recruiting.md
  docs/docs/faster-recruiting.md
Labels: Work in progress

#68 Translate docs/docs/themes.md
  docs/docs/themes.md
Labels: Ready for review

#70 Translation: graphql.md
  docs/docs/graphql.md
Labels: Ready for review

#80 Added 'starter' and 'component shadowing' to the translation glossary #7
  TRANSLATION.md
Labels: Ready for review

#47 Adding translation to working-with-gifs.md
  docs/docs/working-with-gifs.md
Labels: in review

#91 Translated docs/adding-comments.md
  docs/docs/adding-comments.md
Labels: Ready for review

#87 [Translation] Submit to plugin library
  docs/contributing/submit-to-plugin-library.md
Labels: in review

#23 How to run a gatsby workshop.md
  docs/contributing/how-to-run-a-gatsby-workshop.md
Labels: in review

#90 [Ready for review] Added translation to add-page-metadata.md
  docs/docs/add-page-metadata.md
Labels: in review

#107 Translate tutorial part seven
  docs/tutorial/part-seven/index.md
Labels: in review

#109 Adding search
  docs/docs/adding-search.md
Labels: Ready for review

#25 Update gatsby-es / docs / docs / eslint.md
  docs/docs/eslint.md
Labels: in review

#45 Translate build-caching.md
  docs/docs/build-caching.md
Labels: in review

#54 Docs/add custom webpack config
  docs/docs/add-custom-webpack-config.md
Labels: in review

#108 Adding analytics
  docs/docs/adding-analytics.md
Labels: in review

#88 Translated docs/tutorial/authentication-tutorial.md
  docs/tutorial/authentication-tutorial.md
Labels: in review

#113 Translate tutorial/gatsby-image-tutorial
  docs/tutorial/gatsby-image-tutorial/index.md
Labels: in review

#110 Global css
  docs/docs/global-css.md
Labels: Ready for review

#82 Added workshop & starter as new terms + translation.
  TRANSLATION.md
Labels: in review

#73 Translated docs/docs/add-a-manifest-file.md
  docs/docs/add-a-manifest-file.md
Labels: in review

#69 Adding translation to convincing-others.md
  docs/docs/convincing-others.md
Labels: in review

#67 Translate using-an-online-dev-environment.md to Spanish
  docs/contributing/using-an-online-dev-environment.md
Labels: in review

#64 Adding translation to visual-testing-with-storybook.md
  docs/docs/visual-testing-with-storybook.md
Labels: in review

#42 Translate contributing/how-to-write-a-stub.md
  docs/contributing/how-to-write-a-stub.md
Labels: in review

#30 Update using-multiple-gatsby-themes.md
  docs/docs/themes/using-multiple-gatsby-themes.md
Labels: in review

#72 Translated docs/docs/adding-an-rss-feed.md file to spanish
  docs/docs/adding-an-rss-feed.md
Labels: in review

#115 Tutorial part 5
  docs/tutorial/part-five/index.md
Labels: in review

#119 Translate `docs/docs/sourcing-from-wordpress.md`
  docs/docs/sourcing-from-wordpress.md
Labels: in review

#124 Translated to Spanish the adding-pagination.md page
  docs/docs/adding-pagination.md
Labels: in review

#122 Translation of docs/docs/add-seo-component.md completed
  docs/docs/add-seo-component.md
Labels: in review

#126 Translation of adding-a-list-of-markdown-blog-posts completed
  docs/docs/adding-a-list-of-markdown-blog-posts.md
Labels: in review

#132 Docs/adding page transitions
  docs/docs/adding-page-transitions.md
Labels: in review

#130 Translated to Spanish the answering-it-security.md page
  docs/docs/answering-it-security.md
Labels: in review

#118 Translate docs styled components
  docs/docs/styled-components.md
Labels: in review

#133 [Add] Translation of `docs/docs/sourcing-from-sanity.md`
  docs/docs/sourcing-from-sanity.md
Labels: in review

#131 Translation of docs/docs/adding-tags-and-categories-to-blog-posts.md completed
  docs/docs/adding-tags-and-categories-to-blog-posts.md
Labels: in review
